name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Quality Check and SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest coverage flake8

      - name: Run Linter
        run: |
          flake8 . --max-line-length=120 || true

      - name: Run Tests and Generate Coverage
        run: |
          coverage run -m pytest
          coverage report
          coverage xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # Optional CD Job (only runs if CI succeeds)
  # Uncomment and customize based on your deployment target
  # deploy:
  #   name: Deploy Application
  #   runs-on: ubuntu-latest
  #   needs: ci
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4
  #
  #     - name: Deploy (example: to PythonAnywhere / Heroku / EC2)
  #       run: echo "Add your deployment script here"
